# Generated by Django 3.1.5 on 2021-01-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(default='', max_length=30, unique=True)),
                ('altname', models.CharField(default='', max_length=100, unique=True)),
                ('subterms', models.CharField(default='', max_length=200)),
                ('definitions', models.CharField(default='', max_length=1000)),
                ('category', models.CharField(default='', max_length=200)),
                ('topic', models.CharField(default='', max_length=200)),
                ('creator', models.CharField(default='', max_length=1000)),
                ('users_can_add_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('stack', models.CharField(default='', max_length=30)),
                ('when_to_use', models.CharField(default='', max_length=100, unique=True)),
                ('best_features', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
    ]
