# Generated by Django 3.1.5 on 2021-01-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='card',
            name='definitions',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
