# Generated by Django 3.1.5 on 2021-01-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0002_auto_20210112_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='when_to_use',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
