# Generated by Django 3.1.5 on 2021-01-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0003_auto_20210112_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='users_can_add_data',
            field=models.BooleanField(default=True),
        ),
    ]
