# Generated by Django 3.1.5 on 2021-01-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0004_auto_20210112_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='definitions',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
