# Generated by Django 3.1.5 on 2021-01-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0006_remove_card_definitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
