# Generated by Django 3.1.5 on 2021-01-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0007_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='external_resource',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='feature',
            name='page',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='stack_field',
            field=models.CharField(default='', max_length=100),
        ),
    ]
