# Generated by Django 3.1.5 on 2021-01-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0008_auto_20210113_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='codeSnippet',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='card',
            name='definitions',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
