# Generated by Django 3.1.5 on 2021-01-14 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0009_auto_20210113_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Code_Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=3000)),
                ('url', models.CharField(blank=True, default='', max_length=3000)),
                ('creator', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=3000)),
                ('creator', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, default='', max_length=200)),
                ('alt_text', models.CharField(blank=True, default='', max_length=100)),
                ('creator', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(blank=True, default='', max_length=100)),
                ('creator', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50, unique=True)),
                ('subheading', models.CharField(blank=True, default='', max_length=75)),
                ('content', models.CharField(blank=True, default='', max_length=2000)),
                ('creator', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='category',
        ),
        migrations.RemoveField(
            model_name='card',
            name='codeSnippet',
        ),
        migrations.RemoveField(
            model_name='card',
            name='definitions',
        ),
        migrations.AddField(
            model_name='card',
            name='img',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='language',
            name='cards',
            field=models.ManyToManyField(to='interview_api.Card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='altname',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='creator',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='card',
            name='subterms',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='term',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='feature',
            name='external_resource',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='feature',
            name='page',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='stack_field',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='best_features',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='stack',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='language',
            name='when_to_use',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='interview_api.Card')),
                ('categories', models.ManyToManyField(to='interview_api.Category')),
                ('code_Snippets', models.ManyToManyField(to='interview_api.Code_Snippet')),
                ('concepts', models.ManyToManyField(to='interview_api.Concept')),
                ('images', models.ManyToManyField(to='interview_api.Image')),
                ('languages', models.ManyToManyField(to='interview_api.Language')),
                ('resources', models.ManyToManyField(to='interview_api.Resource')),
                ('texts', models.ManyToManyField(to='interview_api.Text')),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=3000)),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_api.card')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='cards',
            field=models.ManyToManyField(to='interview_api.Card'),
        ),
        migrations.AddField(
            model_name='concept',
            name='categories',
            field=models.ManyToManyField(to='interview_api.Category'),
        ),
        migrations.AddField(
            model_name='concept',
            name='code_Snippets',
            field=models.ManyToManyField(to='interview_api.Code_Snippet'),
        ),
        migrations.AddField(
            model_name='concept',
            name='images',
            field=models.ManyToManyField(to='interview_api.Image'),
        ),
        migrations.AddField(
            model_name='concept',
            name='languages',
            field=models.ManyToManyField(to='interview_api.Language'),
        ),
        migrations.AddField(
            model_name='concept',
            name='resources',
            field=models.ManyToManyField(to='interview_api.Resource'),
        ),
        migrations.AddField(
            model_name='concept',
            name='texts',
            field=models.ManyToManyField(to='interview_api.Text'),
        ),
        migrations.AddField(
            model_name='card',
            name='categories',
            field=models.ManyToManyField(to='interview_api.Category'),
        ),
        migrations.AddField(
            model_name='card',
            name='code_snippets',
            field=models.ManyToManyField(to='interview_api.Code_Snippet'),
        ),
        migrations.AddField(
            model_name='card',
            name='images',
            field=models.ManyToManyField(to='interview_api.Image'),
        ),
        migrations.AddField(
            model_name='card',
            name='resources',
            field=models.ManyToManyField(to='interview_api.Resource'),
        ),
        migrations.AddField(
            model_name='card',
            name='texts',
            field=models.ManyToManyField(to='interview_api.Text'),
        ),
        migrations.AddField(
            model_name='language',
            name='categories',
            field=models.ManyToManyField(to='interview_api.Category'),
        ),
        migrations.AddField(
            model_name='language',
            name='code_Snippets',
            field=models.ManyToManyField(to='interview_api.Code_Snippet'),
        ),
        migrations.AddField(
            model_name='language',
            name='images',
            field=models.ManyToManyField(to='interview_api.Image'),
        ),
        migrations.AddField(
            model_name='language',
            name='resources',
            field=models.ManyToManyField(to='interview_api.Resource'),
        ),
        migrations.AddField(
            model_name='language',
            name='texts',
            field=models.ManyToManyField(to='interview_api.Text'),
        ),
    ]
