# Generated by Django 3.1.5 on 2021-01-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0010_auto_20210114_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
