# Generated by Django 3.1.5 on 2021-01-22 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0011_auto_20210121_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-01-21 20:10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='kind',
            field=models.CharField(default='Card', editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.CharField(default='Category', editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='code_snippet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code_snippet',
            name='kind',
            field=models.CharField(default='Code_Snippet', editable=False, max_length=13),
        ),
        migrations.AddField(
            model_name='concept',
            name='kind',
            field=models.CharField(default='Concept', editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name='definition',
            name='kind',
            field=models.CharField(default='Definition', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='feature',
            name='kind',
            field=models.CharField(default='Feature', editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='kind',
            field=models.CharField(default='Image', editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name='language',
            name='kind',
            field=models.CharField(default='Language', editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='kind',
            field=models.CharField(default='Profile', editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='removedItems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviewLater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviewNow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='savedItems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='kind',
            field=models.CharField(default='Resource', editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='text',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='kind',
            field=models.CharField(default='Text', editable=False, max_length=4),
        ),
    ]
